services:
  - type: web
    name: careercompass-server
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: careercompass-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: careercompass-db
    plan: free
